### ISSUE TITLE
AttributeError: CROP_SIZE

### ISSUE THREAD

**Issue by txyxju1997** [tridivb/slowfast_feature_extractor#20]
hello, i have a question, when i run 'python run_net.py --cfg ./configs/SLOWFAST_8x8_R50.yaml' to extract my video features, the problem of AttributeError: CROP_SIZE that confuses me. Thanks!

Traceback (most recent call last):
  File "run_net.py", line 25, in <module>
    main()
  File "run_net.py", line 21, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=test)
  File "/home/XX/slowfast/slowfast/utils/misc.py", line 311, in launch_job
    func(cfg=cfg)
  File "/home/XX/slowfast_feature_extractor/test_net.py", line 94, in test
    model = build_model(cfg)
  File "/home/XX/slowfast_feature_extractor/models/build.py", line 61, in build_model
    cfg.DATA.CROP_SIZE // 32 // pool_size[0][1],
  File "/home/XX/anaconda3/envs/slowfast/lib/python3.8/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: CROP_SIZE

**Comment by csorg** [comment]
Hi, I also met this question. Do you solve it?

**Comment by divineSix** [comment]
Likewise, I was also able to reproduce this issue. Temporarily, I've bypassed it by altering the code referring to CROP_SIZE as TEST_CROP_SIZE, which is present in the config.

**Comment by tridivb** [comment]
Hello, Thank you for noticing this. Admittedly, I have not been maintaining this repo and hence the code might be out of date from the latest slowfast codebase which might cause conflicts. I will try to update it if I am free in the near future and look to solving the issue for the long term.
