### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'cfg_file'

### ISSUE THREAD

**Issue by Dev-ori** [tridivb/slowfast_feature_extractor#21]
Hi I've got this error when i run on this command.

**python run_net.py --cfg ./configs/SLOWFAST_8x8_R50.yaml**

would you please check how to get over from this error?

Traceback (most recent call last):
  File "run_net.py", line 25, in <module>
    main()
  File "run_net.py", line 17, in main
    cfg = load_config(args)
  File "/home/ddf/PycharmProjects/sfex/slowfast/slowfast_feature_extractor/configs/custom_config.py", line 57, in load_config
    if args.cfg_file is not None:
AttributeError: 'Namespace' object has no attribute 'cfg_file

**Comment by polinli** [comment]
In /configs/custom_config.py", line 50,51.
Change args.cfg_file to args.cfg_files.
